image: 'debian:stable'

before_script:
  - apt-get update
  - apt-get -y install --no-install-recommends make sisu

pages:
  stage: deploy
  script:
    - export LANG="C.UTF-8"
    - export LC_ALL="C.UTF-8"
    - make build FORMATS=html
    - mv build/manual/ public/
  when: always
  artifacts:
    paths:
      - public
  only:
    - master
  except:
    - schedules
